// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const TRUSTED_SUPABASE_URL = 'https://bilmgibljmdervrzqldr.supabase.co';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const SUPABASE_URL =
  import.meta.env['NEXT_PUBLIC_SUPABASE_URL'] ||
  (typeof process !== 'undefined' ? process.env['NEXT_PUBLIC_SUPABASE_URL'] : undefined);
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env['NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'] ||
  import.meta.env['NEXT_PUBLIC_SUPABASE_ANON_KEY'] ||
  (typeof process !== 'undefined' ? process.env['NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'] : undefined) ||
  (typeof process !== 'undefined' ? process.env['NEXT_PUBLIC_SUPABASE_ANON_KEY'] : undefined);

const MISSING_KEYS = [
  ...(!SUPABASE_URL ? ['NEXT_PUBLIC_SUPABASE_URL'] : []),
  ...(!SUPABASE_PUBLISHABLE_KEY ? ['NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY or NEXT_PUBLIC_SUPABASE_ANON_KEY'] : []),
];

export const isSupabaseConfigured = Boolean(
  SUPABASE_URL === TRUSTED_SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY,
);
export const supabaseConfigError = !isSupabaseConfigured
  ? !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? `Missing Supabase environment variable(s): ${MISSING_KEYS.join(' and ')}. Set them in Vercel or your local environment.`
    : `Invalid NEXT_PUBLIC_SUPABASE_URL. Expected ${TRUSTED_SUPABASE_URL} but received ${SUPABASE_URL}.`
  : undefined;

function createSupabaseClient() {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const message = `Missing Supabase environment variable(s): ${MISSING_KEYS.join(' and ')}. Set them in Vercel or your local environment.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (SUPABASE_URL !== TRUSTED_SUPABASE_URL) {
    const message = `Invalid NEXT_PUBLIC_SUPABASE_URL. Expected ${TRUSTED_SUPABASE_URL} but received ${SUPABASE_URL}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

